In [48]:
import numpy as np
from ncon import ncon
import cotengra as ctg

In [35]:
A = np.random.randn(2, 2, 2, 2)
B = np.random.randn(2, 2)
C = np.random.randn(2)

In [38]:
C_np = np.einsum(A, (0,2,0,3), B, (3, 2), C, (1,))

In [39]:
C_np

array([ 0.18898441, -0.85493847])

In [45]:
C_ncon = ncon((A, B, C), ((1,3,1,4), (4,3), (-1,)), forder=[-1])

In [46]:
C_ncon

array([ 0.18898441, -0.85493847])

In [61]:
contraction_schedule = [(0,2,0,3), (3, 2), (1,)]
free_indices = [1]

In [69]:
labels = list(map(ctg.get_symbol, np.unique([lab for interac in contraction_schedule for lab in interac] + free_indices)))
inputs = [list(map(ctg.get_symbol, interac)) for interac in contraction_schedule]
output = list(map(ctg.get_symbol, free_indices))

In [70]:
labels

['a', 'b', 'c', 'd']

In [65]:
opt = ctg.HyperOptimizer()

In [73]:
tree = opt.search(inputs, output, size_dict)

In [75]:
tree.contract([A,B,C])

array([ 0.18898441, -0.85493847])

In [77]:
operators = [A, B, C]

In [85]:
size_dict = {}
for (i, interac) in enumerate(contraction_schedule_ncon):
    for a in range(len(interac)):
        size_dict[ctg.get_symbol(interac[a])] = operators[i].shape[a]

NameError: name 'contraction_schedule_ncon' is not defined

In [84]:
size_dict

{'a': 2, 'c': 2, 'd': 2, 'b': 2}